import { Platform, StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#000' },
  topOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    paddingHorizontal: 16,
    paddingTop: Platform.OS === 'android' ? 8 : 0,
  },
  sourceToggle: {
    flexDirection: 'row',
    backgroundColor: 'rgba(0,0,0,0.6)',
    borderRadius: 20,
    padding: 3,
    gap: 2,
  },
  toggleBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 16,
    paddingHorizontal: 10,
    paddingVertical: 6,
    gap: 4,
  },
  toggleBtnActive: { backgroundColor: '#0274DF' },
  toggleText: { fontSize: 12, color: '#9CA3AF' },
  toggleTextActive: { color: '#fff', fontWeight: '600' },
  sosBtn: {
    backgroundColor: '#EF4444',
    borderRadius: 40,
    width: 56,
    height: 56,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 4,
    shadowColor: '#EF4444',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.5,
    shadowRadius: 4,
  },
  sosBtnText: { color: '#fff', fontWeight: '800', fontSize: 14, letterSpacing: 0.5 },
  boundingBox: {
    position: 'absolute',
    borderWidth: 2,
    borderRadius: 4,
  },
  labelBadge: {
    position: 'absolute',
    top: -22,
    left: 0,
    borderRadius: 4,
    paddingHorizontal: 6,
    paddingVertical: 2,
    maxWidth: 160,
  },
  labelText: { color: '#fff', fontSize: 11, fontWeight: '700' },
  warningBanner: {
    position: 'absolute',
    bottom: 100,
    left: 16,
    right: 16,
    backgroundColor: 'rgba(239,68,68,0.92)',
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 10,
    gap: 8,
  },
  warningText: { color: '#fff', fontSize: 14, fontWeight: '600', flex: 1 },
  demoBadge: {
    position: 'absolute',
    bottom: 160,
    alignSelf: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  demoBadgeText: { color: '#F59E0B', fontSize: 10, fontWeight: '700', letterSpacing: 1 },
  otgPlaceholder: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#0F172A',
    gap: 12,
  },
  otgText: { color: '#E5E7EB', fontSize: 16, fontWeight: '600' },
  otgSubtext: { color: '#9CA3AF', fontSize: 13 },
  permissionContainer: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 32,
    gap: 16,
  },
  permissionTitle: { fontSize: 20, fontWeight: '700', color: '#111827' },
  permissionText: { fontSize: 15, color: '#6B7280', textAlign: 'center', lineHeight: 22 },
  permissionBtn: {
    borderRadius: 8,
    minHeight: 44,
    paddingHorizontal: 32,
    justifyContent: 'center',
    alignItems: 'center',
  },
  permissionBtnText: { color: '#fff', fontWeight: '600', fontSize: 16 },
  startRideOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.65)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
  },
  startRideCard: {
    backgroundColor: '#fff',
    borderRadius: 20,
    padding: 28,
    alignItems: 'center',
    width: '100%',
    maxWidth: 320,
  },
  startRideTitle: { fontSize: 18, fontWeight: '700', color: '#111827', marginBottom: 6 },
  startRideSubtitle: {
    fontSize: 14,
    color: '#6B7280',
    textAlign: 'center',
    lineHeight: 20,
    marginBottom: 20,
  },
  startRideBtn: {
    borderRadius: 10,
    height: 48,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  startRideBtnText: { color: '#fff', fontWeight: '700', fontSize: 16 },
});
