import { StyleSheet } from 'react-native';
import { Spacing, Radius, Fonts } from '@/constants/theme';

export const styles = StyleSheet.create({
  container: { flex: 1 },
  center: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.md,
    borderBottomWidth: 1,
  },
  iconBtn: { padding: Spacing.xs },
  headerTitle: { fontSize: 20, fontFamily: Fonts.bold, flex: 1 },
  listContent: { padding: Spacing.md, paddingBottom: 48, gap: Spacing.sm },
  pending: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    padding: Spacing.sm,
    borderRadius: Radius.md,
    backgroundColor: 'rgba(245,158,11,0.15)',
  },
  pendingText: { fontSize: 12, fontFamily: Fonts.medium, color: '#B45309' },
  chips: { gap: Spacing.sm, paddingVertical: Spacing.xs },
  chip: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: Radius.pill,
    borderWidth: 1,
  },
  chipText: { fontSize: 13, fontFamily: Fonts.semibold },
  sectionTitle: { fontSize: 14, fontFamily: Fonts.bold, marginTop: Spacing.sm },
  sectionHint: { fontSize: 11, fontFamily: Fonts.regular, marginBottom: Spacing.xs },
  statsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.sm },
  statCard: {
    width: '48%',
    flexGrow: 1,
    borderRadius: Radius.lg,
    borderWidth: 1,
    padding: Spacing.sm,
    gap: 2,
  },
  statHead: { flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: 4 },
  statLabel: { fontSize: 13, fontFamily: Fonts.bold, flex: 1 },
  statCount: { fontSize: 13, fontFamily: Fonts.bold },
  statLine: { fontSize: 11, fontFamily: Fonts.regular },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    borderRadius: Radius.md,
    borderWidth: 1,
    padding: Spacing.sm,
  },
  rowIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  rowBody: { flex: 1, gap: 2 },
  rowTitle: { fontSize: 14, fontFamily: Fonts.semibold },
  rowMeta: { fontSize: 11, fontFamily: Fonts.regular },
  rowValues: { fontSize: 11, fontFamily: Fonts.medium },
  empty: { alignItems: 'center', padding: Spacing.xl, gap: Spacing.sm },
  emptyText: { fontSize: 13, fontFamily: Fonts.regular, textAlign: 'center' },
});
