import { StyleSheet } from 'react-native';
import { Spacing, Radius, Fonts } from '@/constants/theme';

export const styles = StyleSheet.create({
  container: { flex: 1 },
  center: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.md,
    borderBottomWidth: 1,
  },
  headerTitle: { fontSize: 20, fontFamily: Fonts.bold },
  headerBtns: { flexDirection: 'row', gap: 4 },
  headerBtn: { padding: 4, minHeight: 44, minWidth: 44, alignItems: 'center', justifyContent: 'center' },
  infoBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: Spacing.md,
    paddingVertical: 8,
  },
  infoText: { fontSize: 12, fontFamily: Fonts.regular },
  listContent: { padding: Spacing.md, paddingBottom: 100 },
  contactCard: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: Radius.lg,
    padding: Spacing.md,
    borderWidth: 1,
    gap: 12,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 1,
  },
  contactAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  contactInitial: { fontSize: 18, fontFamily: Fonts.bold },
  contactInfo: { flex: 1, gap: 2 },
  contactName: { fontSize: 15, fontFamily: Fonts.semibold },
  contactPhone: { fontSize: 13, fontFamily: Fonts.regular },
  contactRel: { fontSize: 12, fontFamily: Fonts.regular },
  contactActions: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  deleteBtn: { padding: 4 },
  empty: {
    borderRadius: Radius.xl,
    padding: Spacing.xl,
    alignItems: 'center',
    gap: Spacing.sm,
    marginTop: Spacing.lg,
  },
  emptyTitle: { fontSize: 16, fontFamily: Fonts.bold },
  emptySubtitle: { fontSize: 13, fontFamily: Fonts.regular, textAlign: 'center', lineHeight: 20 },
  emptyBtn: {
    borderRadius: Radius.md,
    height: 44,
    paddingHorizontal: 24,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 8,
  },
  emptyBtnText: { color: '#fff', fontFamily: Fonts.bold, fontSize: 15 },
  modalBackdrop: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(0,0,0,0.5)' },
  modalSheet: {
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: Spacing.lg,
    paddingBottom: 40,
    gap: 16,
  },
  modalHandle: {
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#D1D5DB',
    alignSelf: 'center',
    marginBottom: 4,
  },
  modalTitle: { fontSize: 18, fontFamily: Fonts.bold },
  inputGroup: { gap: 6 },
  inputLabel: { fontSize: 13, fontFamily: Fonts.semibold },
  input: {
    borderRadius: Radius.md,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 15,
    fontFamily: Fonts.regular,
    minHeight: 44,
  },
  modalActions: { flexDirection: 'row', gap: 12, marginTop: 4 },
  modalCancelBtn: {
    flex: 1,
    borderRadius: Radius.md,
    height: 48,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
  },
  modalCancelText: { fontFamily: Fonts.semibold, fontSize: 15 },
  modalSaveBtn: {
    flex: 1,
    borderRadius: Radius.md,
    height: 48,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalSaveText: { color: '#fff', fontFamily: Fonts.bold, fontSize: 15 },
  importBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: Radius.md,
    borderWidth: 1,
    borderStyle: 'dashed',
    justifyContent: 'center',
  },
  importBtnText: { fontFamily: Fonts.semibold, fontSize: 14 },
  pickerModal: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)' },
  pickerSheet: {
    flex: 1,
    marginTop: 60,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    overflow: 'hidden',
  },
  pickerHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.md,
    borderBottomWidth: 1,
  },
  pickerTitle: { fontSize: 17, fontFamily: Fonts.bold },
  pickerCloseBtn: { padding: 4, minWidth: 44, alignItems: 'flex-end' },
  pickerSearch: {
    marginHorizontal: Spacing.md,
    marginVertical: 10,
    borderRadius: Radius.md,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 10,
    fontSize: 15,
    fontFamily: Fonts.regular,
    minHeight: 44,
  },
  pickerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: Spacing.md,
    paddingVertical: 12,
    borderBottomWidth: 1,
  },
  pickerAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pickerInitial: { fontSize: 16, fontFamily: Fonts.bold },
  pickerInfo: { flex: 1 },
  pickerName: { fontSize: 15, fontFamily: Fonts.semibold },
  pickerPhone: { fontSize: 13, fontFamily: Fonts.regular },
  pickerEmpty: {
    alignItems: 'center',
    paddingVertical: 40,
    gap: 8,
  },
  pickerEmptyText: { fontSize: 15, fontFamily: Fonts.regular },
});
