import { StyleSheet } from 'react-native';
import { Spacing, Radius, Fonts } from '@/constants/theme';

export const styles = StyleSheet.create({
  container: { flex: 1 },
  center: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.md,
    borderBottomWidth: 1,
  },
  headerTitle: { fontSize: 20, fontFamily: Fonts.bold },
  headerCount: { fontSize: 13, fontFamily: Fonts.regular },
  listContent: { padding: Spacing.md, paddingBottom: 100 },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: Radius.lg,
    padding: Spacing.md,
    borderWidth: 1,
    gap: 12,
    minHeight: 44,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 1,
  },
  typeIndicator: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  typeDot: { width: 12, height: 12, borderRadius: 6 },
  rowContent: { flex: 1, gap: 2 },
  rowType: { fontSize: 14, fontFamily: Fonts.semibold },
  rowMeta: { fontSize: 12, fontFamily: Fonts.regular },
  rowArea: { fontSize: 12, fontFamily: Fonts.regular },
  rowRight: { alignItems: 'flex-end', gap: 2 },
  confidence: { fontSize: 13, fontFamily: Fonts.monoBold },
  distance: { fontSize: 11, fontFamily: Fonts.regular },
  empty: {
    borderRadius: Radius.xl,
    padding: Spacing.xxl,
    alignItems: 'center',
    gap: Spacing.sm,
    marginTop: Spacing.lg,
  },
  emptyTitle: { fontSize: 16, fontFamily: Fonts.bold },
  emptySubtitle: { fontSize: 13, fontFamily: Fonts.regular, textAlign: 'center', lineHeight: 20 },
  modalBackdrop: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(0,0,0,0.5)' },
  modalSheet: {
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: Spacing.lg,
    paddingBottom: 40,
  },
  modalHandle: {
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#D1D5DB',
    alignSelf: 'center',
    marginBottom: Spacing.md,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: Spacing.md,
  },
  modalTitle: { fontSize: 18, fontFamily: Fonts.bold },
  closeBtn: { padding: 4, minHeight: 44, minWidth: 44, alignItems: 'center', justifyContent: 'center' },
  detailGrid: { gap: 14 },
  detailRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  detailLabel: { fontSize: 13, fontFamily: Fonts.regular, width: 90 },
  detailValue: { fontSize: 13, fontFamily: Fonts.semibold, flex: 1 },
});
