import { StyleSheet } from 'react-native';
import { Spacing, Radius, Fonts } from '@/constants/theme';

export const styles = StyleSheet.create({
  container: { flex: 1 },
  scrollContent: { paddingHorizontal: Spacing.md, paddingTop: Spacing.md },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: Spacing.lg,
  },
  greeting: { fontSize: 14, fontFamily: Fonts.regular, marginBottom: 2 },
  date: { fontSize: 22, fontFamily: Fonts.bold },
  avatarCircle: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: { color: '#fff', fontSize: 18, fontFamily: Fonts.bold },
  card: {
    borderRadius: Radius.lg,
    padding: Spacing.md,
    borderWidth: 1,
    marginBottom: Spacing.md,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 2,
  },
  cardTitle: { fontSize: 11, fontFamily: Fonts.bold, letterSpacing: 0.8, marginBottom: Spacing.sm },
  statusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 6,
    gap: 8,
  },
  statusLabel: { flex: 1, fontSize: 14, fontFamily: Fonts.regular },
  statusValue: { fontSize: 13, fontFamily: Fonts.semibold },
  startButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: Radius.pill,
    height: 52,
    marginBottom: Spacing.md,
  },
  startButtonText: { color: '#fff', fontSize: 16, fontFamily: Fonts.bold },
  statsGrid: {
    flexDirection: 'row',
    gap: Spacing.sm,
    marginBottom: Spacing.md,
  },
  statCard: {
    flex: 1,
    borderRadius: Radius.lg,
    padding: Spacing.md,
    borderWidth: 1,
    alignItems: 'center',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 1,
  },
  statValue: { fontSize: 28, fontFamily: Fonts.monoBold, marginBottom: 2 },
  statLabel: { fontSize: 12, fontFamily: Fonts.medium },
  lastTripHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: Spacing.sm,
  },
  tripMeta: { fontSize: 12, fontFamily: Fonts.regular },
  detectionPills: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginBottom: Spacing.sm },
  pill: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 20,
    paddingHorizontal: 10,
    paddingVertical: 4,
    gap: 5,
  },
  pillDot: { width: 6, height: 6, borderRadius: 3 },
  pillText: { fontSize: 12, fontFamily: Fonts.semibold },
  noDetections: { fontSize: 13, fontFamily: Fonts.regular, marginBottom: Spacing.sm },
  viewHistoryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 2,
    gap: 2,
  },
  viewHistoryText: { fontSize: 13, fontFamily: Fonts.semibold },
  emptyCard: {
    borderRadius: Radius.lg,
    padding: Spacing.xl,
    borderWidth: 1,
    alignItems: 'center',
    gap: Spacing.sm,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 1,
  },
  emptyTitle: { fontSize: 16, fontFamily: Fonts.bold },
  emptySubtitle: { fontSize: 13, fontFamily: Fonts.regular, textAlign: 'center', lineHeight: 20 },
});
