import { StyleSheet } from 'react-native';
import { Spacing, Radius, Fonts } from '@/constants/theme';

export const styles = StyleSheet.create({
  container: { flex: 1 },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.md,
    borderBottomWidth: 1,
  },
  backBtn: { padding: Spacing.xs },
  headerTitle: { fontSize: 20, fontFamily: Fonts.bold, flex: 1 },
  content: { padding: Spacing.md, paddingBottom: 48, gap: Spacing.md },
  card: {
    borderRadius: Radius.lg,
    borderWidth: 1,
    padding: Spacing.md,
    gap: Spacing.sm,
  },
  cardTitle: { fontSize: 15, fontFamily: Fonts.bold },
  row: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  label: { fontSize: 13, fontFamily: Fonts.regular },
  value: { fontSize: 13, fontFamily: Fonts.semibold },
  pill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: Radius.pill,
  },
  pillDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: '#fff' },
  pillText: { color: '#fff', fontSize: 12, fontFamily: Fonts.semibold },
  warning: {
    borderRadius: Radius.md,
    padding: Spacing.sm,
    backgroundColor: 'rgba(245,158,11,0.15)',
  },
  warningText: { fontSize: 12, fontFamily: Fonts.medium, color: '#B45309' },
  liveRow: { flexDirection: 'row', alignItems: 'center', gap: Spacing.md },
  metrics: { flex: 1, gap: 6 },
  actions: { flexDirection: 'row', gap: Spacing.sm },
  actionBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 12,
    borderRadius: Radius.md,
  },
  actionText: { color: '#fff', fontSize: 13, fontFamily: Fonts.semibold },
  outlineBtn: { borderWidth: 1 },
  pairCode: { fontSize: 34, fontFamily: Fonts.bold, letterSpacing: 8, textAlign: 'center' },
  input: {
    flex: 1,
    borderWidth: 1,
    borderRadius: Radius.md,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
    fontFamily: Fonts.regular,
  },
  step: { fontSize: 13, fontFamily: Fonts.regular, lineHeight: 20 },
  eventRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    paddingVertical: 6,
  },
  eventText: { flex: 1, fontSize: 13, fontFamily: Fonts.medium },
  eventTime: { fontSize: 11, fontFamily: Fonts.regular },
});
