import { StyleSheet } from 'react-native';
import { Spacing, Radius } from '@/constants/theme';

export const styles = StyleSheet.create({
  container: { flex: 1 },
  center: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  emptyText: { fontSize: 16 },
  historyCardWrapper: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    paddingHorizontal: Spacing.md,
    paddingTop: Spacing.sm,
  },
  historyCard: {
    borderRadius: Radius.lg,
    padding: Spacing.md,
    borderWidth: 1,
    gap: 6,
  },
  historyTitle: { fontSize: 15, fontWeight: '700' },
  historyMeta: { flexDirection: 'row', gap: Spacing.md },
  metaItem: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  metaText: { fontSize: 13 },
  rideControls: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    alignItems: 'center',
    paddingHorizontal: Spacing.md,
    paddingBottom: 90,
  },
  rideBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: Radius.pill,
    height: 52,
    paddingHorizontal: 32,
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
  },
  rideBtnText: { color: '#fff', fontWeight: '700', fontSize: 16 },
  statsPanel: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    paddingHorizontal: Spacing.md,
  },
  statsScroll: { gap: 8, paddingRight: Spacing.md },
  statCard: {
    backgroundColor: 'rgba(255,255,255,0.92)',
    borderRadius: Radius.md,
    paddingHorizontal: 10,
    paddingVertical: 7,
    minWidth: 80,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.12,
    shadowRadius: 2,
  },
  statCardTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 2,
  },
  statCardCount: { fontSize: 16, fontWeight: '700', color: '#111' },
  statCardLabel: { fontSize: 11, color: '#555', fontWeight: '500' },
  hazardDetailPanel: {
    position: 'absolute',
    left: Spacing.md,
    right: Spacing.md,
    borderRadius: Radius.lg,
    borderWidth: 1,
    padding: Spacing.md,
    gap: 6,
    elevation: 6,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
  },
  hazardDetailHeader: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 4 },
  hazardDetailDot: { width: 10, height: 10, borderRadius: 5 },
  hazardDetailType: { flex: 1, fontSize: 15, fontWeight: '700' },
  hazardDetailClose: { padding: 2 },
  hazardDetailRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  hazardDetailText: { fontSize: 12, flex: 1 },
});
