import { StyleSheet } from 'react-native';
import { Spacing, Radius, Fonts } from '@/constants/theme';

export const styles = StyleSheet.create({
  container: { flex: 1 },
  scrollContent: { paddingHorizontal: Spacing.md, paddingTop: Spacing.md },
  headerTitle: { fontSize: 24, fontFamily: Fonts.bold, marginBottom: Spacing.lg },
  avatarSection: { alignItems: 'center', marginBottom: Spacing.lg, gap: 8 },
  avatarWrapper: {
    position: 'relative',
    marginBottom: 4,
  },
  avatarCircle: {
    width: 80,
    height: 80,
    borderRadius: 40,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  avatarImage: {
    width: 80,
    height: 80,
    borderRadius: 40,
  },
  avatarText: { color: '#fff', fontSize: 28, fontFamily: Fonts.bold },
  avatarEditBadge: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    width: 26,
    height: 26,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#fff',
  },
  avatarUploadOverlay: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 40,
    backgroundColor: 'rgba(0,0,0,0.4)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  fullName: { fontSize: 20, fontFamily: Fonts.bold },
  usernameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  username: { fontSize: 14, fontFamily: Fonts.regular },
  editUsernameBtn: {
    padding: 2,
    minWidth: 28,
    alignItems: 'center',
    justifyContent: 'center',
  },
  usernameEditContainer: {
    width: '100%',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: Spacing.lg,
  },
  usernameInput: {
    width: '100%',
    borderRadius: Radius.md,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 10,
    fontSize: 14,
    fontFamily: Fonts.regular,
    textAlign: 'center',
    minHeight: 44,
  },
  usernameActions: {
    flexDirection: 'row',
    gap: 10,
  },
  saveBtn: {
    flex: 1,
    borderRadius: Radius.md,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  saveBtnText: { fontFamily: Fonts.bold, fontSize: 14, color: '#fff' },
  cancelBtn: {
    flex: 1,
    borderRadius: Radius.md,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
  },
  cancelBtnText: { fontFamily: Fonts.semibold, fontSize: 14 },
  infoCard: {
    borderRadius: Radius.lg,
    borderWidth: 1,
    padding: Spacing.md,
    marginBottom: Spacing.md,
    gap: 0,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 2,
  },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    paddingVertical: 10,
  },
  infoContent: { flex: 1, gap: 2 },
  infoLabel: { fontSize: 12, fontFamily: Fonts.semibold },
  infoValue: { fontSize: 14, fontFamily: Fonts.regular },
  divider: { height: 1, marginHorizontal: -Spacing.md },
  navCard: {
    borderRadius: Radius.lg,
    borderWidth: 1,
    overflow: 'hidden',
    marginBottom: Spacing.md,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 2,
  },
  navRow: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: Spacing.md,
    gap: 12,
    minHeight: 52,
  },
  navLabel: { flex: 1, fontSize: 15, fontFamily: Fonts.medium },
});
